name: smaac_numpy
channels:
  - pytorch
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex
  - blas
  - ca-certificates
  - certifi
  - intel-openmp
  - libffi
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - ninja
  - numpy-base
  - openssl
  - pip
  - python=3.7.10
  - cudatoolkit=10.1.243
  - setuptools
  - six
  - sqlite
  - tk
  - wheel
  - xz
  - zlib
  - pip:
    - cffi
    - chardet
    - cryptography
    - cycler
    - decorator
    - et-xmlfile
    - grid2op
    - lightsim2grid
    - idna
    - jdcal
    - kiwisolver
    - llvmlite
    - matplotlib
    - networkx
    - numba
    - numpy
    - openpyxl
    - packaging
    - pandapower
    - pandas
    - pathlib
    - pillow
    - pybind11
    - pycparser
    - pyparsing
    - python-dateutil
    - pytz
    - requests
    - scipy
    - tqdm 
    - tensorboard
    - tensorboardX
    - urllib3
    - wandb
    - grid2viz
    - xlrd
    - xlsxwriter
    
